name: Release
on:
  push:
    tags:
      ["v*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
    - uses: Adzz/jest_test_action@v1.0.0
      with:
        command: npm install
    - name: Test
    - uses: Adzz/jest_test_action@v1.0.0
      with:
        command: npm test
    - name: Build
    - uses: Adzz/jest_test_action@v1.0.0
      with:
        command: npm build
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: './dist/'
        filename: chrome-extension-snapshot-${{ github.event.release.tag_name }}.zip
    - uses: ncipollo/release-action@v1
      with:
        artifacts: chrome-extension-snapshot-${{ github.event.release.tag_name }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}