name: Release
on:
  push:
    tags:
      ["v*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: Adzz/jest_test_action@v1.0.0
      with:
        package-manager: npm
        command: install
    - uses: Adzz/jest_test_action@v1.0.0
      with:
        package-manager: npm
        command: test
    - uses: Adzz/jest_test_action@v1.0.0
      with:
        package-manager: npm
        command: run-script build
    - uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: './dist/'
        filename: chrome-extension-snapshot-${{ github.event.release.tag_name }}.zip
    - uses: ncipollo/release-action@v1
      with:
        artifacts: chrome-extension-snapshot-${{ github.event.release.tag_name }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
