name: Release
on:
  push:
    tags:
      ["v*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup release
      run: npm install
    - name: Test release
      run: npm test
    - name: Build release
      run: build
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: './dist/'
        filename: chrome-extension-snapshot-${{ github.event.release.tag_name }}.zip
    - uses: ncipollo/release-action@v1
      with:
        artifacts: chrome-extension-snapshot-${{ github.event.release.tag_name }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
